name: Ubuntu GUI with Ngrok – FIXED

on: [workflow_dispatch]

jobs:
  run-vnc:
    runs-on: ubuntu-latest

    steps:
    - name: Install XFCE and VNC
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies tightvncserver

        # إنشاء مجلد مؤقت خاص بنا للباسورد بدل ~/.vnc
        mkdir -p $HOME/myvnc
        echo -ne '\x36\x57\x4c\x77\x7e\x45\x70\x72' > $HOME/myvnc/passwd
        chmod 600 $HOME/myvnc/passwd

        # إعداد ملف xstartup
        mkdir -p $HOME/.vnc
        echo '#!/bin/bash
        startxfce4 &' > $HOME/.vnc/xstartup
        chmod +x $HOME/.vnc/xstartup

        # تشغيل VNC مع تحديد ملف الباسورد الجديد
        vncserver -PasswordFile $HOME/myvnc/passwd :1

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin
        chmod +x /usr/local/bin/ngrok

    - name: Auth Ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok TCP Tunnel
      run: |
        nohup ngrok tcp 5901 > ngrok.log &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json | grep -Po '"public_url":"\K[^"]*'
