name: Ubuntu RDP GPU via Ngrok

on: [workflow_dispatch]

jobs:
  start-desktop:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Install Desktop and VNC
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies tightvncserver

        mkdir -p ~/.vnc
        echo "password" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

        echo "#!/bin/bash
        startxfce4 &" > ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

        vncserver :1

    - name: Install GPU Drivers (Optional)
      run: |
        sudo apt install -y nvidia-driver-470
        nvidia-smi || echo "No GPU available"

    - name: Install and Start Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 5901 > ngrok.log &

    - name: Wait for Ngrok
      run: sleep 10

    - name: Show Ngrok Public URL
      run: |
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        grep -oP '"public_url":"tcp://\K[^"]+' tunnels.json
