name: Ubuntu GUI with Ngrok

on: [workflow_dispatch]

jobs:
  start-vnc:
    runs-on: ubuntu-latest

    steps:
    - name: Install Desktop and VNC
      run: |
        sudo apt update
        sudo apt install xfce4 xfce4-goodies tightvncserver expect -y

        mkdir -p ~/.vnc


        expect <<EOF
        spawn vncpasswd
        expect "Password:"
        send "password\r"
        expect "Verify:"
        send "password\r"
        expect eof
        EOF
        
        echo '#!/bin/bash
        startxfce4 &' > ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup

        vncserver :1

    - name: Install Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin
        chmod +x /usr/local/bin/ngrok

    - name: Authenticate Ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok Tunnel for VNC
      run: |
        nohup ngrok tcp 5901 > ngrok.log &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json | grep -Po '"public_url":"\K[^"]*'
